name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution à minuit chaque jour
  workflow_dispatch:  # Permet l'exécution manuelle

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Update README
        run: |
          echo "<!-- Last updated: $(date) -->" >> README.md
          git add README.md
          git commit -m "Daily commit: $(date)"
          git push 