name: Auto Commit

on:
  schedule:
    - cron: '* * * * *'  # Chaque minute
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update timestamp
        run: |
          # Supprimer l'ancien timestamp
          sed -i '/Last updated:/d' README.md
          # Ajouter le nouveau timestamp
          echo -e "\n### Last updated\n\n$(date -u)" >> README.md
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Auto update: $(date -u)"
          git push 