name: Update README all day at 04:04

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '03 4 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Update README.md file
        run: |
          python auto_commit.py
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Oumllack
          author_email: Oumllack@users.noreply.github.com
          force: true
          signoff: false
          message: ':memo: README.md updated automatically'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 